### ISSUE TITLE
Custom Namespace

### ISSUE THREAD

**Issue by jvv8** [kirschbaum-development/nova-chartjs#33]
I work with a variant Laravel framework where App/Nova/Resource is not the correct namespace.  Is there a way the codebase can be flexible enough to allow for this?

For example, if the Nova Resource model is located at Framework\Nova\Resource, the following error occurs:
```
Class 'App\Nova\Resource' not found {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Class 'App\\Nova\\Resource' not found at [...]/vendor/kirschbaum-development/nova-chartjs/src/Nova/MetricValue.php:11)
```

**Comment by navneetrai** [comment]
@jvv8 Thanks for pointing this out. 

I think I can try to use `Laravel\Nova\Resource` as a base class for this resource.

**Comment by brandonferens** [comment]
@jvv8 This has been fixed and will be released in the next release.

**Comment by vesper8** [comment]
@brandonferens still getting this error, I guess the fix was never released?

```
Class 'App\Nova\Resource' not found
```

You could allow us to specify the location of `Resource` in a configuration file maybe?
